apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.8.4
    helm:
      valuesObject:
        image:
          repository: harbor.use.ucdp.net/quay-proxy/akuity/kargo
        api:
          host: kargo-np.use.ucdp.net
          adminAccount:
            enabled: "false"
          oidc:
            enabled: "true"
            issuerURL: nil ### AzureAD Setup ### The issuer URL for the identity provider. If Dex is enabled, this value will be ignored and the issuer URL will be automatically configured. If Dex is not enabled, this should be set to the issuer URL provided to you by your identity provider.
            clientID: nil ### AzureAD Setup ### The client ID for the OIDC client. If Dex is enabled, this value will be ignored and the client ID will be automatically configured. If Dex is not enabled, this should be set to the client ID provided to you by your identity provider.
            usernameClaim: email ### AzureAD Setup ###  The claim to use as the username for the user.
            admins:
              claims: {} ### AzureAD Setup ###  Subjects having any of these claims will automatically be Kargo admins.
            projectCreators:
              claims: {} ### AzureAD Setup ###  Subjects having any of these claims will automatically receive the permissions of the karo-user role (see api.oidc.users) plus permission to create new Projects. When a Project is created by such a user via the CLI or UI (i.e. through the API and not through kubectl) they will automatically receive admin permissions within that Project as well as permission to update and delete the cluster-scoped Project resource itself.
            users:
              claims: {} ### AzureAD Setup ###  Subjects having any of these claims will automatically receive read-only access to all cluster-scoped Kargo resources. This is the minimum level of permissions that can be granted to a user to allow them to view the list of Projects and system-level configuration. This does not include any access to Secrets.
            viewers:
              claims: {} ### AzureAD Setup ###  Subjects having any of these claims will automatically receive read-only access to all Kargo resources. This does not include any access to Secrets.
          tls:
            enabled: "true"
            selfSignedCert: "true"
            # secretName: "kargo-api-cert" ### Cert/ingress Setup ### Name of the cert Secret to use for the API server. When api.tls.selfSignedCert is true, this will be the name of the generated cert Secret. When api.tls.selfSignedCert is false, a cert Secret with this name must be provided in the same namespace as Kargo. The value in this field has no effect if api.tls.enabled is false.
            # terminatedUpstream: "false" ### Cert/ingress Setup ### Default "false" | Whether TLS is terminated upstream, i.e. a load balancer, reverse-proxy, or an Ingress controller using a single wildcard cert is terminating it. Setting this to true forces all API server URLs to use HTTPS even if the Ingress (if applicable) or API server itself are listening for plain HTTP requests.
          secret:
            name: kargo-api-secret-manual
          ingress:
            enabled: true
            ingressClassName: nginx
            tls:
              enabled: "true"
              selfSignedCert: "true"
              # secretName: "kargo-api-ingress-cert" # Name of the cert Secret for use with the API server's Ingress resource. When api.ingress.tls.selfSignedCert is true, this will be the name of the generated cert Secret. When api.ingress.tls.selfSignedCert is false, a cert Secret with this name must be provided in the same namespace as Kargo. The value in this field has no effect if api.ingress.tls.enabled is false.
            pathType: Prefix
            annotations: # <--- Depending on what our load balancer setup is, may need annotations on the ingress to ensure proper cert configuration
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          argocd:
            urls: 
              "": https://argo-np.use.ucdp.net

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true